name: CI
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'select environment'
        required: true
        default: 'sys'
        type: choice
        options:
          - sys
          - dev
          - prod
      tags:
        description: 'select tags'
        required: true
        default: 'smoke'
        type: choice
        options:
          - Smoke
          - Regression
          - performance
          - security
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Behave test
        run: |
          echo "Running tests in environment: ${{ github.event.inputs.environment }}"
          echo "Running tests with tags: ${{ github.event.inputs.tags }}"

          export TEST_ENV=${{ github.event.inputs.environment }}
          
          if [ "${{ github.event.inputs.tags }}" = "all" ]; then
            behave --define ENV=$TEST_ENV
          else
            behave --tags="${{ github.event.inputs.tags }}" --define ENV=$TEST_ENV
          fi